# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See tools/travis/notes.txt for some guidelines

language: python
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.ccache
addons:
  apt:
    packages:
    - ccache
    - texlive
    - texlive-latex-extra
    - dvipng
    - python-qt4
    # - python3-qt4
    # - python3-qt5
    # - python3-pyside

env:
  global:
    - GH_REF: github.com/scikit-image/docs.git
    - secure: "Z8uxAGrFb6yNw/savI7YvA5/BfkVKVGD3HUkDSXamotJAvUKMjIlWnzLc7d9S7PY99FRENgRYaNw4fzZqwJ91hDITcl1/wk6ux1j778O8kUQZayzdqcJG8KpfBsy1vJ4fl4uDGlSmUP413rR3R3dvvgJzIpCLy2qiQR/xujrGvs="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

matrix:
  include:
    # 2.7 build (until 0.14 is release)
    - os: linux
      python: 2.7
      env: WITH_PYAMG=1 QT=PyQt4
      # Examples need strange versions of Matplotlib and Qt
      # I don't think we should be increasing the minimum version requirement
      # Because somebody is using fancy plotting in an example
    - os: linux
      python: 2.7
      env: MINIMUM_REQUIREMENTS=1
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
      env: QT=PyQt5 WITH_PYAMG=1 OPTIONAL_DEPS=1 BUILD_DOCS=1 DEPLOY_DOCS=1
    - os: osx
      osx_image: xcode9
      language: objective-c
      # OS X has a hard time installing the docs dependencies
      env: TRAVIS_PYTHON_VERSION=3.5 TEST_EXAMPLES=1

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        source tools/travis/osx_install.sh;
      else
        virtualenv -p python ~/venv;
        source ~/venv/bin/activate;
      fi
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - source tools/travis/before_install.sh
    - which python; python --version
    - tools/build_versions.py
    - tools/check_sdist.py

install:
    - python setup.py develop
    # Matplotlib settings - do not show figures during doc examples
    # Where is the matplotlib home on a mac?
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export MPL_DIR=${HOME}/.matplotlib
      else
        export MPL_DIR=${HOME}/.config/matplotlib
      fi
    - mkdir -p ${MPL_DIR}
    - touch ${MPL_DIR}/matplotlibrc
    # Install most of the optional packages
    - |
      if [[ "${OPTIONAL_DEPS}" == "1" ]]; then
        pip install --retries 3 -q -r ./requirements/optional.txt $WHEELHOUSE
      fi
    - |
      if [[ "${WITH_PYAMG}" == "1" ]]; then
        pip install --retries 3 -q pyamg
      fi
    - source tools/travis/install_qt.sh

script:
    - export PY=${TRAVIS_PYTHON_VERSION}
    - flake8 --exit-zero --exclude=test_*,six.py skimage doc/examples viewer_examples
    # run tests again with optional dependencies to get more coverage
    - |
      if [[ "$OPTIONAL_DEPS" == "1" ]]; then
        export TEST_ARGS="${TEST_ARGS} --cov=skimage"
      fi
    # Show what's installed
    - pip list
    - pytest ${TEST_ARGS} skimage
    # Run example applications
    - echo Build or run examples
    - |
      if [[ "${BUILD_DOCS}" == "1" ]]; then
        # requirements/docs.txt fails on Travis OSX
        pip install --retries 3 -q -r ./requirements/docs.txt
        export SPHINXCACHE=${HOME}/.cache/sphinx; make html
      elif [[ "${TEST_EXAMPLES}" != "0" ]]; then
        pip install --retries 3 -q -r ./requirements/docs.txt
        cp $MPL_DIR/matplotlibrc $MPL_DIR/matplotlibrc_backup
        echo 'backend : Template' > $MPL_DIR/matplotlibrc
        for f in doc/examples/*/*.py; do
            python "${f}"
            if [ $? -ne 0 ]; then
                exit 1
            fi
        done
        mv $MPL_DIR/matplotlibrc_backup $MPL_DIR/matplotlibrc
      fi

after_success:
    - codecov
    # Prepare.release
    - doc/release/contribs.py HEAD~10
    - bash tools/travis/deploy_docs.sh
