# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See tools/travis/notes.txt for some guidelines

language: python
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.ccache
addons:
  apt:
    packages:
    - ccache
    - texlive
    - texlive-latex-extra
    - dvipng
    - python-qt4
env:
  global:
    - GH_REF: github.com/scikit-image/docs.git
    - secure: "Z8uxAGrFb6yNw/savI7YvA5/BfkVKVGD3HUkDSXamotJAvUKMjIlWnzLc7d9S7PY99FRENgRYaNw4fzZqwJ91hDITcl1/wk6ux1j778O8kUQZayzdqcJG8KpfBsy1vJ4fl4uDGlSmUP413rR3R3dvvgJzIpCLy2qiQR/xujrGvs="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

matrix:
  include:
    # 2.7 build (until 0.14 is release)
    - os: linux
      python: 2.7
      env: PIP_FLAGS="--pre"
    # Minimum requirement 2.7
    - os: linux
      python: 2.7
      env: WITH_PYAMG=1 MINIMUM_REQUIREMENTS=1 QT=PyQt4
    - os: linux
      python: 2.7
      env: MINIMUM_REQUIREMENTS=1
    - os: linux
      python: 2.7
      env: WITH_PYAMG=1
    - os: linux
      python: 2.7
      env: QT=PyQt4
    - os: linux
      python: 3.4
      env: OPTIONAL_DEPS=1 QT=PySide
    - os: linux
      python: 3.5
    - os: linux
      python: 3.5
      env: PIP_FLAGS="--pre"
    - os: linux
      python: 3.6
      env: BUILD_DOCS=1 DEPLOY_DOCS=1
    # Test the Qt stuff
    - os: linux
      python: 3.6
      env: QT=PyQt4
    - os: linux
      python: 3.6
      env: QT=PySide
    - os: linux
      python: 3.6
      env: QT=PyQt5
      # Add PySide2 when it is finally released
    - os: linux
      python: 3.6
      env: QT=PyQt5 WITH_PYAMG=1 OPTIONAL_DEPS=1
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        source tools/travis/osx_install.sh;
      else
        virtualenv -p python ~/venv;
        source ~/venv/bin/activate;
      fi
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - source tools/travis/before_install.sh
    - which python; python --version
    - tools/build_versions.py
    - tools/check_sdist.py

install:
    - section build
    - python setup.py develop
    - section_end build

script: tools/travis/script.sh

after_success:
    - codecov
    - bash tools/travis/deploy_docs.sh
