# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See tools/travis/notes.txt for some guidelines

language: python
sudo: false

matrix:
  include:
    - os: linux
      env:
        - PLAT=i686
        - MB_PYTHON_VERSION=3.6

before_install: python --version

install: python -c 'import platform; print(platform.architecture())'

script: python --version

