# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See tools/travis/notes.txt for some guidelines

language: python
sudo: required
# Defaullt is 2.7
python: 3.5
services: docker


matrix:
  include:
    - os: linux
      env:
        - PLAT=i686
        - MB_PYTHON_VERSION=3.6
env:
  global:
    - REPO_DIR="scikit-image"

before_install:
  - git clone https://github.com/matthew-brett/multibuild ~/multibuild
  - source ~/multibuild/common_utils.sh
  - source ~/multibuild/travis_steps.sh
  - before_install

install:
  - pwd
  - ls -lah ~/multibuild
  - ls -lah ~/
  - echo $HOME
  - ls -lah
  - build_wheel . $PLAT


script: python --version

